// Generated by Selenium IDE
const { Builder, By, Key, until } = require("selenium-webdriver");
const assert = require("assert");

describe("Testing Bank Accounts Feature - Bank Accounts Creation", function() {
  this.timeout(100000);
  let driver;
  let vars;
  beforeEach(async function() {
    driver = await new Builder().forBrowser("chrome").build();
    vars = {};
  });
  afterEach(async function() {
    await driver.quit();
  });

  it("Test case 1: Happy-path: Creating a bank account with valid data", async function() {
    await driver.get("https://petromiles-frontend.herokuapp.com/");
    await driver
      .manage()
      .window()
      .maximize();
    await driver.findElement(By.id("input-27")).click();
    await driver.findElement(By.id("input-27")).sendKeys("act4@petromiles.com");
    await driver.findElement(By.id("password")).click();
    await driver.findElement(By.id("password")).sendKeys("test1234");

    await driver.findElement(By.css(".theme--dark > .v-btn__content"));

    await driver.findElement(By.css(".theme--dark > .v-btn__content")).click();
    await driver.wait(
      until.elementLocated(
        By.css("div:nth-child(2) > .v-main .v-app-bar__nav-icon .v-icon")
      )
    );
    await driver.sleep(10000).then(async function() {});

    await driver
      .findElement(
        By.css("div:nth-child(2) > .v-main .v-app-bar__nav-icon .v-icon")
      )
      .click();
    await driver.sleep(1000).then(async function() {});

    await driver
      .findElement(
        By.css(
          "div:nth-child(2) > .v-main:nth-child(1) > .v-main__wrap:nth-child(1) > div:nth-child(1) .v-list-item:nth-child(2) .v-list-item__title:nth-child(1)"
        )
      )
      .click();
    await driver.sleep(1000).then(async function() {});

    await driver.findElement(By.css(".mdi-plus:nth-child(2)")).click();
    await driver.sleep(10000).then(async function() {});

    await driver
      .findElement(By.css(".row:nth-child(4) .v-btn__content"))
      .click();
    
    await driver.sleep(5000).then(async function() {});    

    //Type Input
    let input = await driver.findElement(
      By.xpath(
        '//*[@id="app"]/div[1]/main/div/main/div/div[3]/div/div/div[3]/div[2]/div/form/div[1]/div[1]/div/div/div[1]/div[1]/label/following-sibling::input'
      )
    );

    await input.sendKeys("Saving\n");

    // Bank Input
    input = await driver.findElement(
      By.xpath(
        '//*[@id="app"]/div[1]/main/div/main/div/div[3]/div/div/div[3]/div[2]/div/form/div[1]/div[2]/div/div/div[1]/div[1]/label/following-sibling::input'
      )
    );

    await input.sendKeys("Bank of America\n");

    //Account number Input

    input = await driver.findElement(
      By.xpath(
        '//*[@id="app"]/div[1]/main/div/main/div/div[3]/div/div/div[3]/div[2]/div/form/div[2]/div[1]/div/div[2]/div[1]/div/label/following-sibling::input'
      )
    );
    await input.sendKeys("000123456789");

    //  Routing numberInput

    input = await driver.findElement(
      By.xpath(
        '//*[@id="app"]/div[1]/main/div/main/div/div[3]/div/div/div[3]/div[2]/div/form/div[2]/div[2]/div/div[2]/div[1]/div/label/following-sibling::input'
      )
    );
    await input.sendKeys("125000024");

    //Check number Input

    input = await driver.findElement(
      By.xpath(
        '//*[@id="app"]/div[1]/main/div/main/div/div[3]/div/div/div[3]/div[2]/div/form/div[3]/div[1]/div/div[2]/div[1]/div/label/following-sibling::input'
      )
    );
    await input.sendKeys("2235");

    // Nickname Input

    input = await driver.findElement(
      By.xpath(
        '//*[@id="app"]/div[1]/main/div/main/div/div[3]/div/div/div[3]/div[2]/div/form/div[3]/div[2]/div/div[2]/div[1]/div/label/following-sibling::input'
      )
    );
    await input.sendKeys("Bofa-Bank");
    
    await driver.findElement(By.css(".primary:nth-child(2)")).click();
    await driver.sleep(10000).then(async function() {});
  });

  it("Test case 2: Trying to create a bank account with an invalid account number", async function() {
    await driver.get("https://petromiles-frontend.herokuapp.com/");
    await driver
      .manage()
      .window()
      .maximize();
    await driver.findElement(By.id("input-27")).click();
    await driver.findElement(By.id("input-27")).sendKeys("act4@petromiles.com");
    await driver.findElement(By.id("password")).click();
    await driver.findElement(By.id("password")).sendKeys("test1234");

    await driver.findElement(By.css(".theme--dark > .v-btn__content"));

    await driver.findElement(By.css(".theme--dark > .v-btn__content")).click();
    await driver.wait(
      until.elementLocated(
        By.css("div:nth-child(2) > .v-main .v-app-bar__nav-icon .v-icon")
      )
    );
    await driver.sleep(10000).then(async function() {});

    await driver
      .findElement(
        By.css("div:nth-child(2) > .v-main .v-app-bar__nav-icon .v-icon")
      )
      .click();
    await driver.sleep(1000).then(async function() {});

    await driver
      .findElement(
        By.css(
          "div:nth-child(2) > .v-main:nth-child(1) > .v-main__wrap:nth-child(1) > div:nth-child(1) .v-list-item:nth-child(2) .v-list-item__title:nth-child(1)"
        )
      )
      .click();
    await driver.sleep(1000).then(async function() {});

    await driver.findElement(By.css(".mdi-plus:nth-child(2)")).click();
    await driver.sleep(10000).then(async function() {});

    await driver
      .findElement(By.css(".row:nth-child(4) .v-btn__content"))
      .click();
    
    await driver.sleep(5000).then(async function() {});    

    //Type Input
    let input = await driver.findElement(
      By.xpath(
        '//*[@id="app"]/div[1]/main/div/main/div/div[3]/div/div/div[3]/div[2]/div/form/div[1]/div[1]/div/div/div[1]/div[1]/label/following-sibling::input'
      )
    );

    await input.sendKeys("Saving\n");

    // Bank Input
    input = await driver.findElement(
      By.xpath(
        '//*[@id="app"]/div[1]/main/div/main/div/div[3]/div/div/div[3]/div[2]/div/form/div[1]/div[2]/div/div/div[1]/div[1]/label/following-sibling::input'
      )
    );

    await input.sendKeys("Bank of America\n");

    //Account number Input

    input = await driver.findElement(
      By.xpath(
        '//*[@id="app"]/div[1]/main/div/main/div/div[3]/div/div/div[3]/div[2]/div/form/div[2]/div[1]/div/div[2]/div[1]/div/label/following-sibling::input'
      )
    );
    await input.sendKeys("000000000");

    //  Routing numberInput

    input = await driver.findElement(
      By.xpath(
        '//*[@id="app"]/div[1]/main/div/main/div/div[3]/div/div/div[3]/div[2]/div/form/div[2]/div[2]/div/div[2]/div[1]/div/label/following-sibling::input'
      )
    );
    await input.sendKeys("082000073");

    //Check number Input

    input = await driver.findElement(
      By.xpath(
        '//*[@id="app"]/div[1]/main/div/main/div/div[3]/div/div/div[3]/div[2]/div/form/div[3]/div[1]/div/div[2]/div[1]/div/label/following-sibling::input'
      )
    );
    await input.sendKeys("2235");

    // Nickname Input

    input = await driver.findElement(
      By.xpath(
        '//*[@id="app"]/div[1]/main/div/main/div/div[3]/div/div/div[3]/div[2]/div/form/div[3]/div[2]/div/div[2]/div[1]/div/label/following-sibling::input'
      )
    );
    await input.sendKeys("Bofa-Bank-2");
    
    await driver.findElement(By.css(".primary:nth-child(2)")).click();
    await driver.sleep(10000).then(async function() {});
  });

  it("Test case 3: Trying to create a bank account with a routing number that does not match with any american bank", async function() {
    await driver.get("https://petromiles-frontend.herokuapp.com/");
    await driver
      .manage()
      .window()
      .maximize();
    await driver.findElement(By.id("input-27")).click();
    await driver.findElement(By.id("input-27")).sendKeys("act4@petromiles.com");
    await driver.findElement(By.id("password")).click();
    await driver.findElement(By.id("password")).sendKeys("test1234");

    await driver.findElement(By.css(".theme--dark > .v-btn__content"));

    await driver.findElement(By.css(".theme--dark > .v-btn__content")).click();
    await driver.wait(
      until.elementLocated(
        By.css("div:nth-child(2) > .v-main .v-app-bar__nav-icon .v-icon")
      )
    );
    await driver.sleep(10000).then(async function() {});

    await driver
      .findElement(
        By.css("div:nth-child(2) > .v-main .v-app-bar__nav-icon .v-icon")
      )
      .click();
    await driver.sleep(1000).then(async function() {});

    await driver
      .findElement(
        By.css(
          "div:nth-child(2) > .v-main:nth-child(1) > .v-main__wrap:nth-child(1) > div:nth-child(1) .v-list-item:nth-child(2) .v-list-item__title:nth-child(1)"
        )
      )
      .click();
    await driver.sleep(1000).then(async function() {});

    await driver.findElement(By.css(".mdi-plus:nth-child(2)")).click();
    await driver.sleep(10000).then(async function() {});

    await driver
      .findElement(By.css(".row:nth-child(4) .v-btn__content"))
      .click();
    
    await driver.sleep(5000).then(async function() {});    

    //Type Input
    let input = await driver.findElement(
      By.xpath(
        '//*[@id="app"]/div[1]/main/div/main/div/div[3]/div/div/div[3]/div[2]/div/form/div[1]/div[1]/div/div/div[1]/div[1]/label/following-sibling::input'
      )
    );

    await input.sendKeys("Saving\n");

    // Bank Input
    input = await driver.findElement(
      By.xpath(
        '//*[@id="app"]/div[1]/main/div/main/div/div[3]/div/div/div[3]/div[2]/div/form/div[1]/div[2]/div/div/div[1]/div[1]/label/following-sibling::input'
      )
    );

    await input.sendKeys("Bank of America\n");

    //Account number Input

    input = await driver.findElement(
      By.xpath(
        '//*[@id="app"]/div[1]/main/div/main/div/div[3]/div/div/div[3]/div[2]/div/form/div[2]/div[1]/div/div[2]/div[1]/div/label/following-sibling::input'
      )
    );
    await input.sendKeys("000123456789");

    //  Routing numberInput

    input = await driver.findElement(
      By.xpath(
        '//*[@id="app"]/div[1]/main/div/main/div/div[3]/div/div/div[3]/div[2]/div/form/div[2]/div[2]/div/div[2]/div[1]/div/label/following-sibling::input'
      )
    );
    await input.sendKeys("0000000");

    //Check number Input

    input = await driver.findElement(
      By.xpath(
        '//*[@id="app"]/div[1]/main/div/main/div/div[3]/div/div/div[3]/div[2]/div/form/div[3]/div[1]/div/div[2]/div[1]/div/label/following-sibling::input'
      )
    );
    await input.sendKeys("2235");

    // Nickname Input

    input = await driver.findElement(
      By.xpath(
        '//*[@id="app"]/div[1]/main/div/main/div/div[3]/div/div/div[3]/div[2]/div/form/div[3]/div[2]/div/div[2]/div[1]/div/label/following-sibling::input'
      )
    );
    await input.sendKeys("Bofa-Bank-3");
    
    await driver.findElement(By.css(".primary:nth-child(2)")).click();
    await driver.sleep(10000).then(async function() {});
  });

  it("Test case 4: Trying to create a new bank account using an invalid routing number based on the Bank selected.", async function() {
    await driver.get("https://petromiles-frontend.herokuapp.com/");
    await driver
      .manage()
      .window()
      .maximize();
    await driver.findElement(By.id("input-27")).click();
    await driver.findElement(By.id("input-27")).sendKeys("act4@petromiles.com");
    await driver.findElement(By.id("password")).click();
    await driver.findElement(By.id("password")).sendKeys("test1234");

    await driver.findElement(By.css(".theme--dark > .v-btn__content"));

    await driver.findElement(By.css(".theme--dark > .v-btn__content")).click();
    await driver.wait(
      until.elementLocated(
        By.css("div:nth-child(2) > .v-main .v-app-bar__nav-icon .v-icon")
      )
    );
    await driver.sleep(10000).then(async function() {});

    await driver
      .findElement(
        By.css("div:nth-child(2) > .v-main .v-app-bar__nav-icon .v-icon")
      )
      .click();
    await driver.sleep(1000).then(async function() {});

    await driver
      .findElement(
        By.css(
          "div:nth-child(2) > .v-main:nth-child(1) > .v-main__wrap:nth-child(1) > div:nth-child(1) .v-list-item:nth-child(2) .v-list-item__title:nth-child(1)"
        )
      )
      .click();
    await driver.sleep(1000).then(async function() {});

    await driver.findElement(By.css(".mdi-plus:nth-child(2)")).click();
    await driver.sleep(10000).then(async function() {});

    await driver
      .findElement(By.css(".row:nth-child(4) .v-btn__content"))
      .click();
    
    await driver.sleep(5000).then(async function() {});    

    //Type Input
    let input = await driver.findElement(
      By.xpath(
        '//*[@id="app"]/div[1]/main/div/main/div/div[3]/div/div/div[3]/div[2]/div/form/div[1]/div[1]/div/div/div[1]/div[1]/label/following-sibling::input'
      )
    );

    await input.sendKeys("Saving\n");

    // Bank Input
    input = await driver.findElement(
      By.xpath(
        '//*[@id="app"]/div[1]/main/div/main/div/div[3]/div/div/div[3]/div[2]/div/form/div[1]/div[2]/div/div/div[1]/div[1]/label/following-sibling::input'
      )
    );

    await input.sendKeys("Citibank\n");

    //Account number Input

    input = await driver.findElement(
      By.xpath(
        '//*[@id="app"]/div[1]/main/div/main/div/div[3]/div/div/div[3]/div[2]/div/form/div[2]/div[1]/div/div[2]/div[1]/div/label/following-sibling::input'
      )
    );
    await input.sendKeys("000123456789");

    //  Routing numberInput

    input = await driver.findElement(
      By.xpath(
        '//*[@id="app"]/div[1]/main/div/main/div/div[3]/div/div/div[3]/div[2]/div/form/div[2]/div[2]/div/div[2]/div[1]/div/label/following-sibling::input'
      )
    );
    await input.sendKeys("124003116");

    //Check number Input

    input = await driver.findElement(
      By.xpath(
        '//*[@id="app"]/div[1]/main/div/main/div/div[3]/div/div/div[3]/div[2]/div/form/div[3]/div[1]/div/div[2]/div[1]/div/label/following-sibling::input'
      )
    );
    await input.sendKeys("1234");

    // Nickname Input

    input = await driver.findElement(
      By.xpath(
        '//*[@id="app"]/div[1]/main/div/main/div/div[3]/div/div/div[3]/div[2]/div/form/div[3]/div[2]/div/div[2]/div[1]/div/label/following-sibling::input'
      )
    );
    await input.sendKeys("bofa-bank-4");
    
    await driver.findElement(By.css(".primary:nth-child(2)")).click();
    await driver.sleep(10000).then(async function() {});
  });

  it("Test case 5: Trying to create a new bank account without selecting the bank.", async function() {
    await driver.get("https://petromiles-frontend.herokuapp.com/");
    await driver
      .manage()
      .window()
      .maximize();
    await driver.findElement(By.id("input-27")).click();
    await driver.findElement(By.id("input-27")).sendKeys("act4@petromiles.com");
    await driver.findElement(By.id("password")).click();
    await driver.findElement(By.id("password")).sendKeys("test1234");

    await driver.findElement(By.css(".theme--dark > .v-btn__content"));

    await driver.findElement(By.css(".theme--dark > .v-btn__content")).click();
    await driver.wait(
      until.elementLocated(
        By.css("div:nth-child(2) > .v-main .v-app-bar__nav-icon .v-icon")
      )
    );
    await driver.sleep(10000).then(async function() {});

    await driver
      .findElement(
        By.css("div:nth-child(2) > .v-main .v-app-bar__nav-icon .v-icon")
      )
      .click();
    await driver.sleep(1000).then(async function() {});

    await driver
      .findElement(
        By.css(
          "div:nth-child(2) > .v-main:nth-child(1) > .v-main__wrap:nth-child(1) > div:nth-child(1) .v-list-item:nth-child(2) .v-list-item__title:nth-child(1)"
        )
      )
      .click();
    await driver.sleep(1000).then(async function() {});

    await driver.findElement(By.css(".mdi-plus:nth-child(2)")).click();
    await driver.sleep(10000).then(async function() {});

    await driver
      .findElement(By.css(".row:nth-child(4) .v-btn__content"))
      .click();    

    await driver.sleep(5000).then(async function() {});    

    //Type Input
    let input = await driver.findElement(
      By.xpath(
        '//*[@id="app"]/div[1]/main/div/main/div/div[3]/div/div/div[3]/div[2]/div/form/div[1]/div[1]/div/div/div[1]/div[1]/label/following-sibling::input'
      )
    );

    await input.sendKeys("Saving\n");    

    input = await driver.findElement(
      By.xpath(
        '//*[@id="app"]/div[1]/main/div/main/div/div[3]/div/div/div[3]/div[2]/div/form/div[2]/div[1]/div/div[2]/div[1]/div/label/following-sibling::input'
      )
    );
    await input.sendKeys("000123456789");

    //  Routing numberInput

    input = await driver.findElement(
      By.xpath(
        '//*[@id="app"]/div[1]/main/div/main/div/div[3]/div/div/div[3]/div[2]/div/form/div[2]/div[2]/div/div[2]/div[1]/div/label/following-sibling::input'
      )
    );
    await input.sendKeys("021272655");

    //Check number Input

    input = await driver.findElement(
      By.xpath(
        '//*[@id="app"]/div[1]/main/div/main/div/div[3]/div/div/div[3]/div[2]/div/form/div[3]/div[1]/div/div[2]/div[1]/div/label/following-sibling::input'
      )
    );
    await input.sendKeys("1234");

    // Nickname Input

    input = await driver.findElement(
      By.xpath(
        '//*[@id="app"]/div[1]/main/div/main/div/div[3]/div/div/div[3]/div[2]/div/form/div[3]/div[2]/div/div[2]/div[1]/div/label/following-sibling::input'
      )
    );
    await input.sendKeys("bofa-bank-5");
    
    await driver.findElement(By.css(".primary:nth-child(2)")).click();
    await driver.sleep(10000).then(async function() {});
  });

  it("Test case 6: Trying to create a new bank account that has been previously created.", async function() {
    await driver.get("https://petromiles-frontend.herokuapp.com/");
    await driver
      .manage()
      .window()
      .maximize();
    await driver.findElement(By.id("input-27")).click();
    await driver.findElement(By.id("input-27")).sendKeys("act4@petromiles.com");
    await driver.findElement(By.id("password")).click();
    await driver.findElement(By.id("password")).sendKeys("test1234");

    await driver.findElement(By.css(".theme--dark > .v-btn__content"));

    await driver.findElement(By.css(".theme--dark > .v-btn__content")).click();
    await driver.wait(
      until.elementLocated(
        By.css("div:nth-child(2) > .v-main .v-app-bar__nav-icon .v-icon")
      )
    );
    await driver.sleep(10000).then(async function() {});

    await driver
      .findElement(
        By.css("div:nth-child(2) > .v-main .v-app-bar__nav-icon .v-icon")
      )
      .click();
    await driver.sleep(1000).then(async function() {});

    await driver
      .findElement(
        By.css(
          "div:nth-child(2) > .v-main:nth-child(1) > .v-main__wrap:nth-child(1) > div:nth-child(1) .v-list-item:nth-child(2) .v-list-item__title:nth-child(1)"
        )
      )
      .click();
    await driver.sleep(1000).then(async function() {});

    await driver.findElement(By.css(".mdi-plus:nth-child(2)")).click();
    await driver.sleep(10000).then(async function() {});

    await driver
      .findElement(By.css(".row:nth-child(4) .v-btn__content"))
      .click();
    
    await driver.sleep(5000).then(async function() {});    

    //Type Input
    let input = await driver.findElement(
      By.xpath(
        '//*[@id="app"]/div[1]/main/div/main/div/div[3]/div/div/div[3]/div[2]/div/form/div[1]/div[1]/div/div/div[1]/div[1]/label/following-sibling::input'
      )
    );

    await input.sendKeys("Saving\n");

    // Bank Input
    input = await driver.findElement(
      By.xpath(
        '//*[@id="app"]/div[1]/main/div/main/div/div[3]/div/div/div[3]/div[2]/div/form/div[1]/div[2]/div/div/div[1]/div[1]/label/following-sibling::input'
      )
    );

    await input.sendKeys("Bank of America\n");

    //Account number Input

    input = await driver.findElement(
      By.xpath(
        '//*[@id="app"]/div[1]/main/div/main/div/div[3]/div/div/div[3]/div[2]/div/form/div[2]/div[1]/div/div[2]/div[1]/div/label/following-sibling::input'
      )
    );
    await input.sendKeys("000123456789");

    //  Routing numberInput

    input = await driver.findElement(
      By.xpath(
        '//*[@id="app"]/div[1]/main/div/main/div/div[3]/div/div/div[3]/div[2]/div/form/div[2]/div[2]/div/div[2]/div[1]/div/label/following-sibling::input'
      )
    );
    await input.sendKeys("122101706");

    //Check number Input

    input = await driver.findElement(
      By.xpath(
        '//*[@id="app"]/div[1]/main/div/main/div/div[3]/div/div/div[3]/div[2]/div/form/div[3]/div[1]/div/div[2]/div[1]/div/label/following-sibling::input'
      )
    );
    await input.sendKeys("2235");

    // Nickname Input

    input = await driver.findElement(
      By.xpath(
        '//*[@id="app"]/div[1]/main/div/main/div/div[3]/div/div/div[3]/div[2]/div/form/div[3]/div[2]/div/div[2]/div[1]/div/label/following-sibling::input'
      )
    );
    await input.sendKeys("Bofa-Bank-6");
    
    await driver.findElement(By.css(".primary:nth-child(2)")).click();
    await driver.sleep(10000).then(async function() {});
  });
});
